spring.application.name=auth
server.port=9096
spring.datasource.url=jdbc:mysql://localhost:3306/bd_users?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=BaseDeDatos0808
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=ac3dag36g581b1d59f84g2g9fa5g561hh7fa3d7c
