spring.application.name=clientes

#DB
spring.datasource.url=jdbc:mysql://localhost:3306/bd_cliente?createDatabaseIfNotExist=true&serverTimezone=America/Santiago
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#Liquibase
spring.liquibase.change-log=db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true
The file 'classpath:db/changelog/db.changelog.sql
#Conexion con otro microservicio (en caso de tener)

#JWT
jwt.secret=ac3dag36g581b1d59f84g2g9fa5g561hh7fa3d7c

#Puerto
server.port=8083

