server:

spring:
  main:
    web-application-type: reactive

  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://localhost:9080
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: clientes
          uri: http://localhost:9081
          predicates:
            - Path=/api/clientes/**

        - id: compra
          uri: http://localhost:9082
          predicates:
            - Path=/api/compras/**

        - id: inventario
          uri: http://localhost:9083
          predicates:
            - Path=/api/inventario/**

        - id: pagos
          uri: http://localhost:9084
          predicates:
            - Path=/api/pagos/**

        - id: producto
          uri: http://localhost:9085
          predicates:
            - Path=/api/producto/**

        - id: recomendaciones
          uri: http://localhost:9086
          predicates:
            - Path=/api/recomendaciones/**

        - id: posventa
          uri: http://localhost:9087
          predicates:
            - Path=/api/posventa/**

<<<<<<< Updated upstream:gateway/src/main/resources/application.yml
        - id: envios
          uri: http://localhost:9088
          predicates:
            - Path=/api/envios/**

        - id: notificacion
          uri: http://localhost:9089
          predicates:
            - Path=/api/notificacion/**

        - id: fidelizacion
          uri: http://localhost:9090
          predicates:
            - Path=/api/fidelizacion/**
=======
        - id: delivery
          uri: http://localhost:9100
          predicates:
            - Path=/api/delivery/**
>>>>>>> Stashed changes:gateway/gateway/src/main/resources/application.yml

logging:
  file:
    name: ../../logs/gateway.log
  pattern:
    console: "%d{HH:mm:ss} %-5level %msg%n"
    file: "%d{HH:mm:ss} %-5level %msg%n"

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html