spring.application.name=gateway
server.port=8080

# Ruta 1 - Compra
spring.cloud.gateway.server.webmvc.routes[0].id=compra-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/compras,/api/compras/**

# Ruta 2 - Inventario
spring.cloud.gateway.server.webmvc.routes[1].id=inventario-service
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/inventario,/api/inventario/**