spring:
  cloud:
    gateway:
      routes:
        - id: compra
          uri: http://compra:9091
          predicates:
            - Path=/api/compras/**

        - id: inventario
          uri: http://inventario:9092
          predicates:
            - Path=/api/inventario/**

        - id: clientes
          uri: http://clientes:9093
          predicates:
            - Path=/api/clientes/**

        - id: pagos
          uri: http://pagos:9094
          predicates:
            - Path=/api/pagos/**

        - id: producto
          uri: http://producto:9095
          predicates:
            - Path=/api/producto/**

        - id: auth
          uri: http://auth:9096
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        - id: recomendaciones
          uri: http://recomendaciones:9098
          predicates:
            - Path=/api/recomendaciones/**
            
        - id: posventa
          uri: http://posventa:9099
          predicates:
            - Path=/api/posventa/**

        - id: delivery
          uri: http://delivery:9100
          predicates:
            - Path=/api/delivery/**