server:
  port: 9090

spring:
  main:
    web-application-type: reactive

  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: compra
          uri: http://localhost:9091
          predicates:
            - Path=/api/compras/**

        - id: inventario
          uri: http://localhost:9092
          predicates:
            - Path=/api/inventario/**

        - id: clientes
          uri: http://localhost:9093
          predicates:
            - Path=/api/clientes/**

        - id: pagos
          uri: http://localhost:9094
          predicates:
            - Path=/api/pagos/**

        - id: producto
          uri: http://localhost:9095
          predicates:
            - Path=/api/producto/**

        - id: auth
          uri: http://localhost:9096
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        - id: recomendaciones
          uri: http://localhost:9098
          predicates:
            - Path=/api/recomendaciones/**

        - id: posventa
          uri: http://localhost:9099
          predicates:
            - Path=/api/posventa/**

logging:
  file:
    name: ../../logs/gateway.log
  pattern:
    console: "%d{HH:mm:ss} %-5level %msg%n"
    file: "%d{HH:mm:ss} %-5level %msg%n"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html