spring.application.name=compra

#DB
spring.datasource.url=jdbc:mysql://localhost:3306/bd_compras?createDatabaseIfNotExist=true&serverTimezone=America/Santiago
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#Liquibase
spring.liquibase.change-log=db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true
#Conexion con otro microservicio (en caso de tener)
gateway.url=http://localhost:9090

#LOGGER
logging.file.name=logs/compras.log
logging.pattern.console=%d{HH:mm:ss} %-5level %msg%n
logging.pattern.file=%d{HH:mm:ss} %-5level %msg%n

#Puerto
server.port=9091

