spring.application.name=compra

#DB
spring.datasource.url=jdbc:mysql://localhost:3306/bd_compras?createDatabaseIfNotExist=true&serverTimezone=America/Santiago
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#Liquibase
spring.liquibase.change-log=db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true
#Conexion con otro microservicio (en caso de tener)
api.cliente.exists=http://localhost:9090/api/clientes/%d/exists
api.producto.exists=http://localhost:9090/api/producto/%d/exists

#JWT
jwt.secret=ac3dag36g581b1d59f84g2g9fa5g561hh7fa3d7c

#LOGGER
logging.file.name=logs/compra.log
logging.pattern.console=%d{HH:mm:ss} %-5level %msg%n
logging.pattern.file=%d{HH:mm:ss} %-5level %msg%n

#Puerto
server.port=9091

