spring.application.name=recomendaciones
server.port=9098

# Conexión a BD - Creación automática si no existe e integración Docker
spring.datasource.url=jdbc:mysql://localhost:3306/bd_recomendaciones
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración JPA e Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# URL del API Gateway (todas las llamadas entre microservicios pasan por aquí)
gateway.url=http://localhost:9090

# Configuración de Logs apuntando a la carpeta raíz compartida
logging.file.name=logs/recomendaciones.log
logging.pattern.console=%d{HH:mm:ss} %-5level %msg%n
logging.pattern.file=%d{HH:mm:ss} %-5level %msg%n

# Habilitar documentación Swagger/OpenAPI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

